Fix nightly tests (#259)
* add upgrade

* add explicit homebrew setup

* link python 3.10 to python 3

* make python version a string

* add debug

* split up steps

* downgrade to python 3.9 to match formulae dependency

* testing manually updating python dependency

* back to 3.10

* add curl to path

* remove verbose logging

* break apart install

* downgrade python dependency

* test python version

* more updates

* next try

* remove python setup

* Update installation-tests.yml

* remove upgrade

* wip

* more symlink issues

* try 12

* use macos-11

* remove some extra bits

* add back or true

* clean up and add back in all adapters

diff --git a/.github/workflows/installation-tests.yml b/.github/workflows/installation-tests.yml
--- a/.github/workflows/installation-tests.yml
+++ b/.github/workflows/installation-tests.yml
@@ -29,21 +29,34 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        adapter:
-          ["dbt-postgres", "dbt-redshift", "dbt-snowflake", "dbt-bigquery"]
-        os: [macos-latest]
+        adapter: ['dbt-postgres', 'dbt-redshift', 'dbt-snowflake', 'dbt-bigquery']
+        os: [macos-11]
 
     runs-on: ${{ matrix.os }}
 
     steps:
-      - name: Brew install ${{ matrix.adapter }}
+      
+      - name: "Prepare Brew"
+        # brew upgrade generates some symlink update warnings that cause failures without the || true.
+        # They're just that the symlink wasn't updated which is okay to ignore.
+        # This does cause other errors to be ignored but for this case that's safe since the brew install
+        # step would likely fail at that point.
         run: |
           brew update
-          brew install git
+          brew upgrade || true
+      
+      - name: "Check installed"
+        run: brew list
+      
+      - name: "Brew Tap"
+        run: |
           brew tap dbt-labs/dbt
+
+      - name: "Brew install ${{ matrix.adapter }}"
+        run: |
           brew install --verbose ${{ matrix.adapter }}
 
-      - name: Verify ${{ matrix.adapter }} version
+      - name: "Verify ${{ matrix.adapter }} version"
         run: |
           dbt --version
 
